# fly.toml app configuration file generated for dna-analyzer-api on 2023-09-26T13:03:50-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dna-analyzer-api"
primary_region = "qro"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
